version: 2.1
jobs:
  build-and-test:  
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'test'
workflows:
  iytest:  
    jobs:
      - build-and-test
